"use strict";

module.exports = {
  "rules": {
    // Strict Mode
    "strict": 0,
    // Variables
    "init-declarations": 0,
    "no-catch-shadow": 2,
    "no-delete-var": 2,
    "no-label-var": 2,
    "no-restricted-globals": 2,
    "no-shadow": 2,
    "no-shadow-restricted-names": 2,
    "no-undef": 2,
    "no-undef-init": 2,
    "no-undefined": 2,
    "no-unused-vars": 2,
    "no-use-before-define": 2,
    // Stylistic Issues
    "array-bracket-newline": 0,
    "array-bracket-spacing": 0,
    "array-element-newline": 0,
    "block-spacing": 2,
    "brace-style": [ 2, "1tbs", { "allowSingleLine": true }],
    "camelcase": 0,
    "capitalized-comments": 2,
    "comma-dangle": 2,
    "comma-spacing": 2,
    "comma-style": 2,
    "computed-property-spacing": 2,
    "consistent-this": 2,
    "eol-last": 0,
    "func-call-spacing": 2,
    "func-name-matching": 2,
    "func-names": [ 2, "as-needed"],
    "func-style": [ 2, "expression", { "allowArrowFunctions": true }],
    "function-paren-newline": [ 2, "multiline" ],
    "id-blacklist": [
      "error",
      "data",
      "err",
      "e",
      "cb",
      "callback",
      "res",
      "response"
    ],
    "id-length": [ 2, { "min": 2 }],
    "id-match": 0,
    "indent": [ "error", 2 ],
    "jsx-quotes": 2,
    "key-spacing": 2,
    "keyword-spacing": 2,
    "line-comment-position": 2,
    "linebreak-style": 2,
    "lines-around-comment": 2,
    "max-depth": 2,
    "max-len": 2,
    "max-lines": [ 2, {
      "skipBlankLines": true,
      "skipComments": true
    }],
    "max-nested-callbacks": 2,
    "max-params": 2,
    "max-statements": [ 2, 10, { "ignoreTopLevelFunctions": true }],
    "max-statements-per-line": 2,
    "multiline-ternary": 0,
    "new-cap": 2,
    "new-parens": 2,
    "newline-per-chained-call": 2,
    "no-array-constructor": 2,
    "no-bitwise": 2,
    "no-continue": 2,
    "no-inline-comments": 2,
    "no-lonely-if": 2,
    "no-mixed-operators": 2,
    "no-mixed-spaces-and-tabs": 2,
    "no-multi-assign": 2,
    "no-multiple-empty-lines": 2,
    "no-negated-condition": 2,
    "no-nested-ternary": 0,
    "no-new-object": 2,
    "no-plusplus": 2,
    "no-restricted-syntax": 0,
    "no-tabs": 2,
    "no-ternary": 0,
    "no-trailing-spaces": 2,
    "no-underscore-dangle": 2,
    "no-unneeded-ternary": 2,
    "no-whitespace-before-property": 2,
    "no-whitespace-before-property": 2,
    "object-curly-newline": 2,
    "object-curly-spacing": [ 2, "always" ],
    "object-property-newline": 2,
    "one-var": 0,
    "one-var-declaration-per-line": 2,
    "operator-assignment": 2,
    "operator-linebreak": [ 2, "before" ],
    "padded-blocks": [ 2, "never" ],
    "padding-line-between-statements": 0,
    "quote-props": 2,
    "quotes": [ 2, "double", {
      "allowTemplateLiterals": true,
      "avoidEscape": true
    }],
    "require-jsdoc": [ 2, {
      "require": {
        "ArrowFunctionExpression": false,
        "ClassDeclaration": false,
        "FunctionDeclaration": false,
        "MethodDefinition": false
      }
    }],
    "semi": 2,
    "semi-spacing": 2,
    "semi-style": 2,
    "sort-keys": 0,
    "sort-vars": 2,
    "space-before-blocks": 2,
    "space-before-function-paren": [ 2, "never" ],
    "space-in-parens": [ 2, "never" ],
    "space-infix-ops": 2,
    "space-unary-ops": [ 2, {
      "words": true,
      "nonwords": false
    }],
    "spaced-comment": 2,
    "switch-colon-spacing": 2,
    "template-tag-spacing": 2,
    "unicode-bom": 2,
    "wrap-regex": 2
  }
};
